introduce Doxygen for reference manual

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3560,7 +3560,7 @@ fi
 # 	Produce outputs
 # -----------------------------------------------------------------------
 
-ac_config_files="$ac_config_files makedefs makedirs odc/Makefile hqp_docp/Makefile"
+ac_config_files="$ac_config_files makedefs makedirs odc/Makefile hqp_docp/Makefile doc/Doxyfile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -3896,7 +3896,8 @@ do
   "makedirs" ) CONFIG_FILES="$CONFIG_FILES makedirs" ;;
   "odc/Makefile" ) CONFIG_FILES="$CONFIG_FILES odc/Makefile" ;;
   "hqp_docp/Makefile" ) CONFIG_FILES="$CONFIG_FILES hqp_docp/Makefile" ;;
-  *) { { echo "$as_me:3899: error: invalid argument: $ac_config_target" >&5
+  "doc/Doxyfile" ) CONFIG_FILES="$CONFIG_FILES doc/Doxyfile" ;;
+  *) { { echo "$as_me:3900: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -4151,7 +4152,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:4154: creating $ac_file" >&5
+    { echo "$as_me:4155: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -4169,7 +4170,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:4172: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:4173: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -4182,7 +4183,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:4185: error: cannot find input file: $f" >&5
+           { { echo "$as_me:4186: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
