add compile flag for backwards compatibility of Tcl 8.4

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3127,6 +3127,9 @@ cat >>confdefs.h <<\EOF
 #define USE_TCL_STUBS 1
 EOF
 
+# only use new const's by Tcl 8.4 that are backwards compatible to Tcl 8.1
+IF_DEFS="-DUSE_COMPAT_CONST=1 $IF_DEFS"
+
 # -----------------------------------------------------------------------
 # 	Configure ADOL-C
 # -----------------------------------------------------------------------
@@ -3157,7 +3160,7 @@ OMU_INTRKSUITE_C=""
 RKSUITE_O=""
 RKSUITE_COMPILE_CMD=""
 
-echo "$as_me:3160: checking --enable-fortran" >&5
+echo "$as_me:3163: checking --enable-fortran" >&5
 echo $ECHO_N "checking --enable-fortran... $ECHO_C" >&6
 # Check whether --enable-fortran or --disable-fortran was given.
 if test "${enable_fortran+set}" = set; then
@@ -3166,13 +3169,13 @@ if test "${enable_fortran+set}" = set; then
 else
   omu_fortran=no
 fi;
-echo "$as_me:3169: result: $omu_fortran" >&5
+echo "$as_me:3172: result: $omu_fortran" >&5
 echo "${ECHO_T}$omu_fortran" >&6
 
 if test "$omu_fortran" != no; then
   # Extract the first word of "f77", so it can be a program name with args.
 set dummy f77; ac_word=$2
-echo "$as_me:3175: checking for $ac_word" >&5
+echo "$as_me:3178: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_fortran_f77+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -3189,7 +3192,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_fortran_f77="$ac_dir/$ac_word"
-   echo "$as_me:3192: found $ac_dir/$ac_word" >&5
+   echo "$as_me:3195: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -3200,10 +3203,10 @@ fi
 fortran_f77=$ac_cv_path_fortran_f77
 
 if test -n "$fortran_f77"; then
-  echo "$as_me:3203: result: $fortran_f77" >&5
+  echo "$as_me:3206: result: $fortran_f77" >&5
 echo "${ECHO_T}$fortran_f77" >&6
 else
-  echo "$as_me:3206: result: no" >&5
+  echo "$as_me:3209: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -3212,7 +3215,7 @@ fi
   else
     # Extract the first word of "g77", so it can be a program name with args.
 set dummy g77; ac_word=$2
-echo "$as_me:3215: checking for $ac_word" >&5
+echo "$as_me:3218: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_fortran_g77+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -3229,7 +3232,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_fortran_g77="$ac_dir/$ac_word"
-   echo "$as_me:3232: found $ac_dir/$ac_word" >&5
+   echo "$as_me:3235: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -3240,17 +3243,17 @@ fi
 fortran_g77=$ac_cv_path_fortran_g77
 
 if test -n "$fortran_g77"; then
-  echo "$as_me:3243: result: $fortran_g77" >&5
+  echo "$as_me:3246: result: $fortran_g77" >&5
 echo "${ECHO_T}$fortran_g77" >&6
 else
-  echo "$as_me:3246: result: no" >&5
+  echo "$as_me:3249: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
     if test ! -z "$fortran_g77"; then
       fortran_ftn="g77"
     else
-      { { echo "$as_me:3253: error: \"Require f77 or g77 to enable RKsuite.\"" >&5
+      { { echo "$as_me:3256: error: \"Require f77 or g77 to enable RKsuite.\"" >&5
 echo "$as_me: error: \"Require f77 or g77 to enable RKsuite.\"" >&2;}
    { (exit 1); exit 1; }; }
     fi
@@ -3267,18 +3270,18 @@ echo "$as_me: error: \"Require f77 or g77 to enable RKsuite.\"" >&2;}
     OMU_INTDASPK_C="Omu_IntDASPK.C"
     DASPK="daspk"
     DASPK_OBJS="../daspk/solver/*.o ../daspk/preconds/*.o"
-    echo "$as_me:3270: result: enabling DASPK" >&5
+    echo "$as_me:3273: result: enabling DASPK" >&5
 echo "${ECHO_T}enabling DASPK" >&6
   fi
 
   # default settings with RKsuite
   OMU_INTRKSUITE_C="Omu_IntRKsuite.C"
   RKSUITE_O="`pwd`/rksuite/rksuite.o"
-  echo "$as_me:3277: result: enabling RKsuite" >&5
+  echo "$as_me:3280: result: enabling RKsuite" >&5
 echo "${ECHO_T}enabling RKsuite" >&6
 
   # try to figure out Fortran environment
-  echo "$as_me:3281: checking for pow_dd in -lf2c" >&5
+  echo "$as_me:3284: checking for pow_dd in -lf2c" >&5
 echo $ECHO_N "checking for pow_dd in -lf2c... $ECHO_C" >&6
 if test "${ac_cv_lib_f2c_pow_dd+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -3286,7 +3289,7 @@ else
   ac_check_lib_save_LIBS=$LIBS
 LIBS="-lf2c  $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
-#line 3289 "configure"
+#line 3292 "configure"
 #include "confdefs.h"
 
 /* Override any gcc2 internal prototype to avoid an error.  */
@@ -3305,16 +3308,16 @@ pow_dd ();
 }
 _ACEOF
 rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:3308: \"$ac_link\"") >&5
+if { (eval echo "$as_me:3311: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
-  echo "$as_me:3311: \$? = $ac_status" >&5
+  echo "$as_me:3314: \$? = $ac_status" >&5
   (exit $ac_status); } &&
          { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:3314: \"$ac_try\"") >&5
+  { (eval echo "$as_me:3317: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:3317: \$? = $ac_status" >&5
+  echo "$as_me:3320: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   ac_cv_lib_f2c_pow_dd=yes
 else
@@ -3325,7 +3328,7 @@ fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-echo "$as_me:3328: result: $ac_cv_lib_f2c_pow_dd" >&5
+echo "$as_me:3331: result: $ac_cv_lib_f2c_pow_dd" >&5
 echo "${ECHO_T}$ac_cv_lib_f2c_pow_dd" >&6
 if test $ac_cv_lib_f2c_pow_dd = yes; then
   fortran_lib=f2c
@@ -3333,7 +3336,7 @@ else
   fortran_lib=""
 fi
 
-  echo "$as_me:3336: checking for pow_dd in -lg2c" >&5
+  echo "$as_me:3339: checking for pow_dd in -lg2c" >&5
 echo $ECHO_N "checking for pow_dd in -lg2c... $ECHO_C" >&6
 if test "${ac_cv_lib_g2c_pow_dd+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -3341,7 +3344,7 @@ else
   ac_check_lib_save_LIBS=$LIBS
 LIBS="-lg2c  $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
-#line 3344 "configure"
+#line 3347 "configure"
 #include "confdefs.h"
 
 /* Override any gcc2 internal prototype to avoid an error.  */
@@ -3360,16 +3363,16 @@ pow_dd ();
 }
 _ACEOF
 rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:3363: \"$ac_link\"") >&5
+if { (eval echo "$as_me:3366: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
-  echo "$as_me:3366: \$? = $ac_status" >&5
+  echo "$as_me:3369: \$? = $ac_status" >&5
   (exit $ac_status); } &&
          { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:3369: \"$ac_try\"") >&5
+  { (eval echo "$as_me:3372: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:3372: \$? = $ac_status" >&5
+  echo "$as_me:3375: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   ac_cv_lib_g2c_pow_dd=yes
 else
@@ -3380,14 +3383,14 @@ fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-echo "$as_me:3383: result: $ac_cv_lib_g2c_pow_dd" >&5
+echo "$as_me:3386: result: $ac_cv_lib_g2c_pow_dd" >&5
 echo "${ECHO_T}$ac_cv_lib_g2c_pow_dd" >&6
 if test $ac_cv_lib_g2c_pow_dd = yes; then
   fortran_lib=g2c
 fi
 
   if test "${fortran_f77}" = "f77"; then
-    echo "$as_me:3390: checking for pow_dd in -lftn" >&5
+    echo "$as_me:3393: checking for pow_dd in -lftn" >&5
 echo $ECHO_N "checking for pow_dd in -lftn... $ECHO_C" >&6
 if test "${ac_cv_lib_ftn_pow_dd+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -3395,7 +3398,7 @@ else
   ac_check_lib_save_LIBS=$LIBS
 LIBS="-lftn  $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
-#line 3398 "configure"
+#line 3401 "configure"
 #include "confdefs.h"
 
 /* Override any gcc2 internal prototype to avoid an error.  */
@@ -3414,16 +3417,16 @@ pow_dd ();
 }
 _ACEOF
 rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:3417: \"$ac_link\"") >&5
+if { (eval echo "$as_me:3420: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
-  echo "$as_me:3420: \$? = $ac_status" >&5
+  echo "$as_me:3423: \$? = $ac_status" >&5
   (exit $ac_status); } &&
          { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:3423: \"$ac_try\"") >&5
+  { (eval echo "$as_me:3426: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:3426: \$? = $ac_status" >&5
+  echo "$as_me:3429: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   ac_cv_lib_ftn_pow_dd=yes
 else
@@ -3434,7 +3437,7 @@ fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-echo "$as_me:3437: result: $ac_cv_lib_ftn_pow_dd" >&5
+echo "$as_me:3440: result: $ac_cv_lib_ftn_pow_dd" >&5
 echo "${ECHO_T}$ac_cv_lib_ftn_pow_dd" >&6
 if test $ac_cv_lib_ftn_pow_dd = yes; then
   fortran_lib=ftn
@@ -3470,7 +3473,7 @@ fi
 # 	Configure support for MEX
 # -----------------------------------------------------------------------
 
-echo "$as_me:3473: checking --enable-mex" >&5
+echo "$as_me:3476: checking --enable-mex" >&5
 echo $ECHO_N "checking --enable-mex... $ECHO_C" >&6
 # Check whether --enable-mex or --disable-mex was given.
 if test "${enable_mex+set}" = set; then
@@ -3479,7 +3482,7 @@ if test "${enable_mex+set}" = set; then
 else
   omu_mex=no
 fi;
-echo "$as_me:3482: result: $omu_mex" >&5
+echo "$as_me:3485: result: $omu_mex" >&5
 echo "${ECHO_T}$omu_mex" >&6
 
 MEX_SRCS=""
@@ -3490,7 +3493,7 @@ MEX_LIBS=""
 
 if test "$omu_mex" != no; then
 
-  echo "$as_me:3493: checking --with-matlab" >&5
+  echo "$as_me:3496: checking --with-matlab" >&5
 echo $ECHO_N "checking --with-matlab... $ECHO_C" >&6
 
 # Check whether --with-matlab or --without-matlab was given.
@@ -3498,10 +3501,10 @@ if test "${with_matlab+set}" = set; then
   withval="$with_matlab"
   with_matlab=$withval
 fi;
-  echo "$as_me:3501: result: $with_matlab" >&5
+  echo "$as_me:3504: result: $with_matlab" >&5
 echo "${ECHO_T}$with_matlab" >&6
 
-  echo "$as_me:3504: checking --with-matlab-libs" >&5
+  echo "$as_me:3507: checking --with-matlab-libs" >&5
 echo $ECHO_N "checking --with-matlab-libs... $ECHO_C" >&6
 
 # Check whether --with-matlab-libs or --without-matlab-libs was given.
@@ -3509,7 +3512,7 @@ if test "${with_matlab_libs+set}" = set; then
   withval="$with_matlab_libs"
   with_matlab_libs=$withval
 fi;
-  echo "$as_me:3512: result: $with_matlab_libs" >&5
+  echo "$as_me:3515: result: $with_matlab_libs" >&5
 echo "${ECHO_T}$with_matlab_libs" >&6
 
   if test ! -z "${with_matlab}"; then
@@ -3560,7 +3563,7 @@ echo "${ECHO_T}$with_matlab_libs" >&6
     OMU_DEFS="$OMU_DEFS -DOMU_WITH_MEX=1"
   fi
   if test -z "${MEX_LIBDIR}"; then
-    { { echo "$as_me:3563: error: for --enable-mex need --with-matlab and --with-matlab-libs" >&5
+    { { echo "$as_me:3566: error: for --enable-mex need --with-matlab and --with-matlab-libs" >&5
 echo "$as_me: error: for --enable-mex need --with-matlab and --with-matlab-libs" >&2;}
    { (exit 1); exit 1; }; }
   fi
@@ -3580,7 +3583,7 @@ fi
 # defaults to disable GNU malloc
 GMALLOC_O=""
 
-echo "$as_me:3583: checking --enable-gmalloc" >&5
+echo "$as_me:3586: checking --enable-gmalloc" >&5
 echo $ECHO_N "checking --enable-gmalloc... $ECHO_C" >&6
 # Check whether --enable-gmalloc or --disable-gmalloc was given.
 if test "${enable_gmalloc+set}" = set; then
@@ -3589,11 +3592,11 @@ if test "${enable_gmalloc+set}" = set; then
 else
   odc_gmalloc=no
 fi;
-echo "$as_me:3592: result: $odc_gmalloc" >&5
+echo "$as_me:3595: result: $odc_gmalloc" >&5
 echo "${ECHO_T}$odc_gmalloc" >&6
 
 if test "$odc_gmalloc" = no; then
-  echo "$as_me:3596: checking if malloc returns NULL" >&5
+  echo "$as_me:3599: checking if malloc returns NULL" >&5
 echo $ECHO_N "checking if malloc returns NULL... $ECHO_C" >&6
   ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
@@ -3605,7 +3608,7 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
   odc_gmalloc=yes
 else
   cat >conftest.$ac_ext <<_ACEOF
-#line 3608 "configure"
+#line 3611 "configure"
 #include "confdefs.h"
 
   #include <stdlib.h>
@@ -3618,15 +3621,15 @@ else
 
 _ACEOF
 rm -f conftest$ac_exeext
-if { (eval echo "$as_me:3621: \"$ac_link\"") >&5
+if { (eval echo "$as_me:3624: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
-  echo "$as_me:3624: \$? = $ac_status" >&5
+  echo "$as_me:3627: \$? = $ac_status" >&5
   (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
-  { (eval echo "$as_me:3626: \"$ac_try\"") >&5
+  { (eval echo "$as_me:3629: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:3629: \$? = $ac_status" >&5
+  echo "$as_me:3632: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   odc_gmalloc=no
 else
@@ -3637,7 +3640,7 @@ odc_gmalloc=yes
 fi
 rm -f core core.* *.core conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
-  echo "$as_me:3640: result: $odc_gmalloc" >&5
+  echo "$as_me:3643: result: $odc_gmalloc" >&5
 echo "${ECHO_T}$odc_gmalloc" >&6
 fi
 if test "$odc_gmalloc" != no; then
@@ -3645,7 +3648,7 @@ if test "$odc_gmalloc" != no; then
 fi
 
 if test "$GMALLOC_O" != ""; then
-  echo "$as_me:3648: result: enabling GNU malloc" >&5
+  echo "$as_me:3651: result: enabling GNU malloc" >&5
 echo "${ECHO_T}enabling GNU malloc" >&6
 fi
 
@@ -3653,7 +3656,7 @@ fi
 # 	Configure support for CUTE
 # -----------------------------------------------------------------------
 
-echo "$as_me:3656: checking --enable-cute" >&5
+echo "$as_me:3659: checking --enable-cute" >&5
 echo $ECHO_N "checking --enable-cute... $ECHO_C" >&6
 # Check whether --enable-cute or --disable-cute was given.
 if test "${enable_cute+set}" = set; then
@@ -3662,7 +3665,7 @@ if test "${enable_cute+set}" = set; then
 else
   hqp_cute=no
 fi;
-echo "$as_me:3665: result: $hqp_cute" >&5
+echo "$as_me:3668: result: $hqp_cute" >&5
 echo "${ECHO_T}$hqp_cute" >&6
 
 if test "$hqp_cute" != no; then
@@ -3676,7 +3679,7 @@ fi
 # 	Configure support for Ascend
 # -----------------------------------------------------------------------
 
-echo "$as_me:3679: checking --enable-ascend" >&5
+echo "$as_me:3682: checking --enable-ascend" >&5
 echo $ECHO_N "checking --enable-ascend... $ECHO_C" >&6
 # Check whether --enable-ascend or --disable-ascend was given.
 if test "${enable_ascend+set}" = set; then
@@ -3685,7 +3688,7 @@ if test "${enable_ascend+set}" = set; then
 else
   hqp_ascend=no
 fi;
-echo "$as_me:3688: result: $hqp_ascend" >&5
+echo "$as_me:3691: result: $hqp_ascend" >&5
 echo "${ECHO_T}$hqp_ascend" >&6
 
 if test "$hqp_ascend" != no; then
@@ -3709,7 +3712,7 @@ fi
 # if installed (see www.graphviz.org)
 # Extract the first word of "dot", so it can be a program name with args.
 set dummy dot; ac_word=$2
-echo "$as_me:3712: checking for $ac_word" >&5
+echo "$as_me:3715: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_DOT+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -3726,7 +3729,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_DOT="$ac_dir/$ac_word"
-   echo "$as_me:3729: found $ac_dir/$ac_word" >&5
+   echo "$as_me:3732: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -3737,10 +3740,10 @@ fi
 DOT=$ac_cv_path_DOT
 
 if test -n "$DOT"; then
-  echo "$as_me:3740: result: $DOT" >&5
+  echo "$as_me:3743: result: $DOT" >&5
 echo "${ECHO_T}$DOT" >&6
 else
-  echo "$as_me:3743: result: no" >&5
+  echo "$as_me:3746: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -3864,7 +3867,7 @@ rm -f confdef2opt.sed
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:3867: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:3870: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -4032,7 +4035,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:4035: error: ambiguous option: $1
+    { { echo "$as_me:4038: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -4051,7 +4054,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:4054: error: unrecognized option: $1
+  -*) { { echo "$as_me:4057: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -4092,7 +4095,7 @@ do
   "odc/Makefile" ) CONFIG_FILES="$CONFIG_FILES odc/Makefile" ;;
   "odc/mex.tcl" ) CONFIG_FILES="$CONFIG_FILES odc/mex.tcl" ;;
   "doc/Doxyfile" ) CONFIG_FILES="$CONFIG_FILES doc/Doxyfile" ;;
-  *) { { echo "$as_me:4095: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:4098: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -4355,7 +4358,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:4358: creating $ac_file" >&5
+    { echo "$as_me:4361: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -4373,7 +4376,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:4376: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:4379: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -4386,7 +4389,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:4389: error: cannot find input file: $f" >&5
+           { { echo "$as_me:4392: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
